# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09d540945c8503503010f3d5e048786b672d88f2eb87020a2bc7d4cb8cd65c94ce612dfefacaf3cac2cc4c259b6ea8daadc6b61d5adf7f55cfc925ec6bf6f346

test:
  secret_key_base: 14f57c22b4ba39b3abb6389f33ade7689204ab61818a8fb7b29168b81ec288edbd8ad1fd1da1ced796bfd49b06bb32d6aa7ee3e809dcdcf15e7ed0e27089cb51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
